name: test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-

      - name: Install HuggingFace CLI
        run: pip install huggingface_hub

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('bun.lock') }}

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run TypeScript and ESLint
        run: bun run check

      - name: Run unit tests
        run: bun test

      - name: Get HuggingFace commit hashes
        id: hf
        run: |
          DATASET_SHA=$(hf datasets info deepsweet/mdn | jq --join-output '.sha')
          MODEL_SHA=$(hf models info deepsweet/bge-m3-GGUF-Q4_K_M | jq --join-output '.sha')

          echo "dataset=$DATASET_SHA" >> "$GITHUB_OUTPUT"
          echo "model=$MODEL_SHA" >> "$GITHUB_OUTPUT"

      - name: Cache HuggingFace
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface/hub
          key: ${{ runner.os }}-huggingface-${{ steps.hf.outputs.dataset }}-${{ steps.hf.outputs.model }}

      - name: Run integration tests
        timeout-minutes: 5
        run: |
          bun run dist
          npx -y . download
          bun run test

      - name: Prune HuggingFace revisions
        if: always()
        run: hf cache prune --yes
