name: update

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-

      - name: Install HuggingFace CLI
        run: pip install huggingface_hub

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout MDN
        run: |
          git clone --no-checkout --depth=1 --filter=tree:0 git@github.com:mdn/content.git data
          cd data
          git sparse-checkout set --no-cone --stdin < ../scripts/checkout.txt
          git checkout
          ls -1 files/en-us/web/

      - name: Get HuggingFace commit hashes
        id: hf
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          DATASET_SHA=$(hf datasets info deepsweet/mdn | jq --join-output '.sha')
          MODEL_SHA=$(hf models info deepsweet/bge-m3-GGUF-Q4_K_M | jq --join-output '.sha')

          echo "dataset=$DATASET_SHA" >> "$GITHUB_OUTPUT"
          echo "model=$MODEL_SHA" >> "$GITHUB_OUTPUT"

      - name: Cache HuggingFace
        uses: actions/cache@v4
        with:
          path: ~/.cache/huggingface/hub
          key: ${{ runner.os }}-huggingface-${{ steps.hf.outputs.dataset }}-${{ steps.hf.outputs.model }}

      - name: Download dataset and model
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: bun run download

      - name: Prune HuggingFace revisions
        if: always()
        run: hf cache prune --yes

      - name: Update dataset
        run: bun run update data/files/en-us/web/

      - name: Upload dataset
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: bun run upload '♻️ monthly autoupdate'

